//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1000Dizi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiletTablosu
    {
        public int bilet_id { get; set; }
        public string bilet_film { get; set; }
        public string bilet_koltuk { get; set; }
        public string bilet_tarih { get; set; }
        public string bilet_saat { get; set; }
        public string bilet_uyeId { get; set; }
    }
}
