//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1000Dizi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    public partial class FilmTablosu
    {

        public int film_id { get; set; }
        [Required]
        public string film_ismi { get; set; }

        [Required]
        [AllowHtml]
        public string film_aciklama { get; set; }
        [Required]
        public string film_vizyon { get; set; }
        public string film_resim { get; set; }
        public virtual HttpPostedFileBase resimFile { get; set; }
    }


}

