//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1000Dizi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeriTabaniEntities : DbContext
    {
        public VeriTabaniEntities()
            : base("name=VeriTabaniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BiletTablosu> BiletTablosu { get; set; }
        public virtual DbSet<FilmTablosu> FilmTablosu { get; set; }
        public virtual DbSet<SeansKoltukTablosu> SeansKoltukTablosu { get; set; }
        public virtual DbSet<SeansTablosu> SeansTablosu { get; set; }
        public virtual DbSet<UyelerTablosu> UyelerTablosu { get; set; }
        public virtual DbSet<KullanicilarTablosu> KullanicilarTablosu { get; set; }
    }
}
