//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1000Dizi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeansKoltukTablosu
    {
        public int seans_id { get; set; }
        public string koltuk_no { get; set; }
        public int id { get; set; }
    }
}
