//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1000Dizi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeansTablosu
    {
        public int seans_id { get; set; }
        public int seans_filmId { get; set; }
        public string seans_tarih { get; set; }
        public string seans_saat { get; set; }
    }
}
