//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1000Dizi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyelerTablosu
    {
        public int uye_id { get; set; }
        public string uye_isim { get; set; }
        public string uye_sifre { get; set; }
    }
}
